---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Asus.
--- DateTime: 2022/6/24 10:04
---

--[[--
    匹配中二级界面
    Matching2nd.lua
]]

local Matching2nd = class("Matching2nd", function()
    return ccui.Layout:create()
end)

local StringDef = require("app.def.StringDef")

--[[--
    @description: 构造函数
    @parma Layer 原来的一级界面
    @return none
]]
function Matching2nd:ctor(Layer)
    self.frameCounter_ = 0 --type: number, 帧计数器，用于帧刷新
    self.circle_ = nil --type: sprite, 转圈的匹配中状态条，用于帧刷新
    self.baseLayer_ = Layer -- type: layer, 这个二级界面基于的界面
    self:init()
end

--[[--
    @description: 初始化，设置界面属性和子节点
    @parma none
    @return none
]]
function Matching2nd:init()
    self:setBackGroundColor(cc.c4b(0, 0, 0, 0))
    self:setBackGroundColorType(1)
    self:setContentSize(display.width, display.height)
    self:setBackGroundColorOpacity(150)
    self:setPosition(0, 0)

    local backSprite = display.newSprite(StringDef.PATH_SECOND_MATCHING_BASE_POPUP)
    backSprite:setPosition(display.width * .5, display.height * .5)
    backSprite:addTo(self)

    local size = backSprite:getContentSize()

    local cancelButton = ccui.Button:create(StringDef.PATH_SECOND_MATCHING_BUTTON_CANCEL)
    cancelButton:setPosition(size.width * .5, size.height * .2)
    cancelButton:addTouchEventListener(function(sender, eventType)
        print("cancel")
        if eventType == 2 then
            self.baseLayer_.twoLevelUi_ = nil
            self:removeSelf()
        end
    end)
    cancelButton:addTo(backSprite)

    local circleSprite = display.newSprite(StringDef.PATH_SECOND_MATCHING_IMAGE)
    circleSprite:setPosition(size.width * .5, size.height * .55)
    circleSprite:addTo(backSprite)

    self.circle_ = circleSprite
    --屏蔽点击
    self:addNodeEventListener(cc.NODE_TOUCH_EVENT, function(event)
        if event.name == "began" then
            return true
        end
    end)
    self:setTouchEnabled(true)


end

--[[--
    @description: 注册监听
    @parma none
    @return none
]]
function Matching2nd:onEnter()

end

--[[--
    @description: 注销监听
    @parma none
    @return none
]]
function Matching2nd:onExit()

end

--[[--
    @description:
    @parma dt type:number, 帧间隔
    @return none
]]
function Matching2nd:update(dt)
    self.circle_:setRotation(1 * self.frameCounter_)
    self.frameCounter_ = (self.frameCounter_ + 1) % 360
end

return Matching2nd
