---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Zoybzo.
--- DateTime: 2022-07-07 12:29
---
local ShopConfirmPurchase2nd = class("ShopConfirmPurchase2nd", function()
    return ccui.Layout:create()
end)
--local
local audio = require("framework.audio")
local StringDef = require("app.def.StringDef")
local ConstDef = require("app.def.ConstDef")

local OutGameData = require("app.data.OutGameData")
local TableUtil = require("app.utils.TableUtil")
local OutGameMsgController = require("app.network.OutGameMsgController")
local MsgDef = require("app.def.MsgDef")
--
--
function ShopConfirmPurchase2nd:ctor(baseLayer, baseButton, commodity, itemWidth, itemHeight)
    self.baseLayer_ = baseLayer -- type: layer, 这个二级界面基于的界面
    self.baseButton_ = baseButton
    self.commodity_ = commodity -- 商品
    self.itemWidth_ = itemWidth
    self.itemHeight_ = itemHeight
    self:initView()
end

--[[--
    @description: 初始化，设置界面属性和子节点
    @parma none
    @return none
]]
function ShopConfirmPurchase2nd:initView()
    local checkLayer = ccui.Layout:create()
    checkLayer:setBackGroundColor(cc.c4b(0, 0, 0, 100))
    checkLayer:setBackGroundColorType(1)
    checkLayer:opacity(200)
    checkLayer:setAnchorPoint(0.5, 0.5)
    checkLayer:setPosition(display.cx, display.cy)
    checkLayer:setContentSize(display.width, display.height)
    checkLayer:addTo(display.getRunningScene())
    -- TODO 尝试一下不设置是否可行
    --checkLayer:setLocalZOrder(1)
    -- 设置层可触摸屏蔽下方按键
    -- 点击二级界面之外的地方关闭
    checkLayer:setTouchEnabled(true)
    checkLayer:addTouchEventListener(function(sender, eventType)
        if 2 == eventType then
            audio.playEffect(StringDef.PATH_BTN_CLICK)
            checkLayer:removeFromParent()
        end
    end)
    -- 设置背景
    local checkBase = cc.Sprite:create(StringDef.PATH_SHOP_SECOND_PURCHASE_CONFIRM_BASE)
    checkBase:setAnchorPoint(0.5, 0.5)
    checkBase:setPosition(display.cx, display.cy)
    checkBase:addTo(checkLayer)
    local sizeSetBase = checkBase:getContentSize()
    -- 点击右上角按钮关闭
    local checkClose = ccui.Button:create(StringDef.PATH_SHOP_SECOND_PURCHASE_CONFIRM_CLOSE)
    checkClose:setAnchorPoint(0.5, 0.5)
    checkClose:setPosition(display.cx + sizeSetBase.width / 2 - sizeSetBase.width / 15,
        display.cy + sizeSetBase.height / 2 - sizeSetBase.height / 8)
    checkClose:addTo(checkLayer)
    checkClose:addTouchEventListener(function(sender, eventType)
        if 2 == eventType then
            audio.playEffect(StringDef.PATH_BTN_CLICK)
            checkLayer:removeFromParent()
        end
    end)
    -- 遮罩，屏蔽点击退出触摸事件
    local baseMaskLayer = ccui.Layout:create()
    baseMaskLayer:setAnchorPoint(0.5, 0.5)
    baseMaskLayer:setPosition(display.cx, display.cy)
    baseMaskLayer:setContentSize(sizeSetBase.width, sizeSetBase.height)
    baseMaskLayer:setTouchEnabled(true)
    baseMaskLayer:addTo(checkLayer, -1)
    -- 确认购买
    local purchaseButton = ccui.Button:create(StringDef.PATH_SHOP_SECOND_PURCHASE_CONFIRM_BUY)
    purchaseButton:setAnchorPoint(0.5, 0.5)
    purchaseButton:setPosition(display.cx, display.cy - sizeSetBase.height * 17 / 48)
    purchaseButton:addTo(checkLayer)
    local commodity = self.commodity_
    local baseLayer = self.baseLayer_
    local itemWidth = self.itemWidth_
    local itemHeight = self.itemHeight_
    local baseButton = self.baseButton_
    purchaseButton:addTouchEventListener(function(sender, eventType)
        if 2 == eventType then
            audio.playEffect(StringDef.PATH_BUY_PAID_ITEM, false)

            local msgUserInfo = {}
            local userInfo = OutGameData:getUserInfo()
            msgUserInfo.userInfoCoinAmount = userInfo:getCoinAmount()
                    - commodity:getCommodityPrice()
            msgUserInfo.userInfoDiamondAmount = userInfo:getDiamondAmount()
            msgUserInfo.userInfoCardList = {}
            table.insert(msgUserInfo.userInfoCardList, TableUtil:removeTableFunction(
                    commodity:getCommodityCommodity()))
            local msg = TableUtil:encapsulateAsMsg(MsgDef.REQTYPE
                    .LOBBY.PURCHASE_COMMODITY, userInfo:getAccount(),
                    "userInfo", msgUserInfo)
            OutGameMsgController:sendMsg(msg)
            _buttonCoinClickGrey(baseLayer, itemWidth, itemHeight, baseButton)
            checkLayer:removeFromParent()
        end
    end)
    -- 价格
    local priceLabel = display.newTTFLabel({
        text = self.commodity_:getCommodityPrice(),
        font = StringDef.PATH_FONT_FZBIAOZJW,
        size = 30
    })
    priceLabel:align(display.CENTER, display.cx + sizeSetBase.width / 20, display.cy - sizeSetBase.height * 17 / 48)
    priceLabel:setColor(cc.c3b(255, 255, 255))
    priceLabel:enableOutline(cc.c4b(0, 0, 0, 255), 1)
    priceLabel:addTo(checkLayer)
    --
    local coinIcon = ccui.Button:create(StringDef.PATH_SHOP_SECOND_PURCHASE_ICON_COIN)
    coinIcon:setAnchorPoint(0.5, 0.5)
    coinIcon:setPosition(display.cx - sizeSetBase.width / 15, display.cy - sizeSetBase.height * 17 / 48)
    coinIcon:addTo(checkLayer)
    -- 商品图
    local dragonSprite = cc.Sprite:create(ConstDef.ICON_TOWER_FRAGMENT[
        self.commodity_:getCommodityCommodity():getCardId()])
    dragonSprite:setAnchorPoint(0.5, 0.5)
    dragonSprite:setPosition(display.cx, display.cy)
    dragonSprite:scale(0.8)
    dragonSprite:addTo(checkLayer)
    -- 商品数量
    local numLabel = display.newTTFLabel({
        text = "X" .. tostring(self.commodity_:getCommodityAmount()),
        font = StringDef.PATH_FONT_FZBIAOZJW,
        size = 25
    })
    numLabel:align(display.CENTER, display.cx, display.cy - sizeSetBase.height * 7 / 48)
    numLabel:setColor(cc.c3b(255, 206, 55))
    numLabel:enableOutline(cc.c4b(0, 0, 0, 255), 1)
    numLabel:addTo(checkLayer)
end

--[[--
    描述：金币商城按钮点击事件(点击后置灰)

    @param layer

    @return none
]]
function _buttonCoinClickGrey(layer, itemWidth, itemHeight, button)
    button:setTouchEnabled(false)
    -- 遮罩
    local shadeSprite = cc.Sprite:create(StringDef.PATH_COIN_SHOP_BASE_SHADE)
    shadeSprite:setPosition(itemWidth * .55, itemHeight * .45)
    shadeSprite:setAnchorPoint(0.5, 0.5)
    shadeSprite:setOpacity(120)
    shadeSprite:addTo(layer)
end

--[[--
    @description: 注册监听
    @parma none
    @return none
]]
function ShopConfirmPurchase2nd:onEnter()

end

--[[--
    @description: 注销监听
    @parma none
    @return none
]]
function ShopConfirmPurchase2nd:onExit()

end

--[[--
    @description:
    @parma dt type:number, 帧间隔
    @return none
]]
function ShopConfirmPurchase2nd:update(dt)

end

return ShopConfirmPurchase2nd
