--[[--
    StringDef.lua
    字符串定义
]]
local StringDef = {
    ---@type string PATH_RES
    PATH_ICON_01 = "res/test/generic/collected/1.png",--图鉴页面，已收集中使用的彩色图标
    PATH_ICON_02 = "res/test/generic/collected/2.png",
    PATH_ICON_03 = "res/test/generic/collected/3.png",
    PATH_ICON_04 = "res/test/generic/collected/4.png",
    PATH_ICON_05 = "res/test/generic/collected/5.png",
    PATH_ICON_06 = "res/test/generic/collected/6.png",
    PATH_ICON_07 = "res/test/generic/collected/7.png",
    PATH_ICON_08 = "res/test/generic/collected/8.png",
    PATH_ICON_09 = "res/test/generic/collected/9.png",
    PATH_ICON_10 = "res/test/generic/collected/10.png",
    PATH_ICON_11 = "res/test/generic/collected/11.png",
    PATH_ICON_12 = "res/test/generic/collected/12.png",
    PATH_ICON_13 = "res/test/generic/collected/13.png",
    PATH_ICON_14 = "res/test/generic/collected/14.png",
    PATH_ICON_15 = "res/test/generic/collected/15.png",
    PATH_ICON_16 = "res/test/generic/collected/16.png",
    PATH_ICON_17 = "res/test/generic/collected/17.png",
    PATH_ICON_18 = "res/test/generic/collected/18.png",
    PATH_ICON_19 = "res/test/generic/collected/19.png",
    PATH_ICON_20 = "res/test/generic/collected/20.png",
    PATH_BASEMAP_AREA = "res/home/guide/subinterface_current_lineup/base_area.png",
    PATH_BASEMAP_TITLE = "res/home/guide/subinterface_current_lineup/base_title.png",
    PATH_NUMBER_1 = "res/home/guide/subinterface_current_lineup/one.png",
    PATH_NUMBER_2 = "res/home/guide/subinterface_current_lineup/two.png",
    PATH_NUMBER_3 = "res/home/guide/subinterface_current_lineup/three.png",
    PATH_TEXTURE_NOWLINEUP = "res/home/guide/subinterface_current_lineup/text_current_lineup.png",
    PATH_BASEMAP_CONNECTION = "res/home/guide/subinterface_current_lineup/base_lineup.png",
    PATH_ICON_CHOOSE = "res/home/guide/subinterface_current_lineup/icon_selected.png",
    PATH_ICON_UNCHOOSE = "res/home/guide/subinterface_current_lineup/icon_unselected.png",
    PATH_BASEMAP_TIP = "res/home/guide/subinterface_tips/base_tips.png",
    PATH_TEXTURE_LONG = "res/home/guide/subinterface_tips/text_tips.png",
    PATH_TEXTURE_SHORT = "res/home/guide/subinterface_tips/text_total_critical_strike_damage.png",
    PATH_SPLITLINE_COLLECTED = "res/home/guide/subinterface_tower_list/split_collected.png",
    PATH_SPLITLINE_UNCOLLECTED = "res/home/guide/subinterface_tower_list/split_not_collected.png",
    
    PATH_ICON_LINEUP_01="res/test/generic/icon_lineup/1.png",--阵容队列中使用的图标
    PATH_ICON_LINEUP_02="res/test/generic/icon_lineup/2.png",                 
    PATH_ICON_LINEUP_03="res/test/generic/icon_lineup/3.png",
    PATH_ICON_LINEUP_04="res/test/generic/icon_lineup/4.png",
    PATH_ICON_LINEUP_05="res/test/generic/icon_lineup/5.png",
    PATH_ICON_LINEUP_06="res/test/generic/icon_lineup/6.png",
    PATH_ICON_LINEUP_07="res/test/generic/icon_lineup/7.png",
    PATH_ICON_LINEUP_08="res/test/generic/icon_lineup/8.png",
    PATH_ICON_LINEUP_09="res/test/generic/icon_lineup/9.png",
    PATH_ICON_LINEUP_10="res/test/generic/icon_lineup/10.png",
    PATH_ICON_LINEUP_11="res/test/generic/icon_lineup/11.png",
    PATH_ICON_LINEUP_12="res/test/generic/icon_lineup/12.png",
    PATH_ICON_LINEUP_13="res/test/generic/icon_lineup/13.png",
    PATH_ICON_LINEUP_14="res/test/generic/icon_lineup/14.png",
    PATH_ICON_LINEUP_15="res/test/generic/icon_lineup/15.png",
    PATH_ICON_LINEUP_16="res/test/generic/icon_lineup/16.png",
    PATH_ICON_LINEUP_17="res/test/generic/icon_lineup/17.png",
    PATH_ICON_LINEUP_18="res/test/generic/icon_lineup/18.png",
    PATH_ICON_LINEUP_19="res/test/generic/icon_lineup/19.png",
    PATH_ICON_LINEUP_20="res/test/generic/icon_lineup/20.png",

    PATH_ICON_UNCOLLECTED_01="res/test/generic/uncollected/1.png",--图鉴界面，未使用中的黑白图标
    PATH_ICON_UNCOLLECTED_02="res/test/generic/uncollected/2.png",
    PATH_ICON_UNCOLLECTED_03="res/test/generic/uncollected/3.png",
    PATH_ICON_UNCOLLECTED_04="res/test/generic/uncollected/4.png",
    PATH_ICON_UNCOLLECTED_05="res/test/generic/uncollected/5.png",
    PATH_ICON_UNCOLLECTED_06="res/test/generic/uncollected/6.png",
    PATH_ICON_UNCOLLECTED_07="res/test/generic/uncollected/7.png",
    PATH_ICON_UNCOLLECTED_08="res/test/generic/uncollected/8.png",
    PATH_ICON_UNCOLLECTED_09="res/test/generic/uncollected/9.png",
    PATH_ICON_UNCOLLECTED_10="res/test/generic/uncollected/10.png",
    PATH_ICON_UNCOLLECTED_11="res/test/generic/uncollected/11.png",
    PATH_ICON_UNCOLLECTED_12="res/test/generic/uncollected/12.png",
    PATH_ICON_UNCOLLECTED_13="res/test/generic/uncollected/13.png",
    PATH_ICON_UNCOLLECTED_14="res/test/generic/uncollected/14.png",
    PATH_ICON_UNCOLLECTED_15="res/test/generic/uncollected/15.png",
    PATH_ICON_UNCOLLECTED_16="res/test/generic/uncollected/16.png",
    PATH_ICON_UNCOLLECTED_17="res/test/generic/uncollected/17.png",
    PATH_ICON_UNCOLLECTED_18="res/test/generic/uncollected/18.png",
    PATH_ICON_UNCOLLECTED_19="res/test/generic/uncollected/19.png",
    PATH_ICON_UNCOLLECTED_20="res/test/generic/uncollected/20.png",
    --

}
return StringDef
