--[[--
    TowerDef.lua

    描述：塔图标信息管理
]]
--local
local StringDef = require("app.def.StringDef")
--
local TowerDef = {
    {

        ICON_PATH = StringDef.PATH_TOWER_01,
        ICON_PATH_GREY = StringDef.PATH_TOWER_GREY_01,
        IS_OBTAIN = true,
        ID = 1,
        RARITY = 1,
        TYPE = 1,
        NAME = "",
        LEVEL = 1,
        SKILLS = {

        },
        ATK_TARGET = 1,
        ATK = 20,
        ATK_UPGRADE = 3,
        ATK_ENHANCE = 10,
        FIRECD = 0.8,
        FIRECD_UPGRADE = 0.01,
        FIRECD_ENHANCE = 0,
        EXTRA_DAMAGE = 20,
        FATALITY_RATE = 0,
    },
    {

        ICON_PATH = StringDef.PATH_TOWER_02,
        ICON_PATH_GREY = StringDef.PATH_TOWER_GREY_02,
        IS_OBTAIN = true,
        ID = 2,
        RARITY = 3,
        TYPE = 1,
        NAME = "",
        LEVEL = 1,
        SKILLS = {

        },
        ATK_TARGET = 1,
        ATK = 20,
        ATK_UPGRADE = 5,
        ATK_ENHANCE = 10,
        FIRECD = 0.8,
        FIRECD_UPGRADE = 0.01,
        FIRECD_ENHANCE = 0,
        EXTRA_DAMAGE = 50,
        FATALITY_RATE = 0,
    },
    {

        ICON_PATH = StringDef.PATH_TOWER_03,
        ICON_PATH_GREY = StringDef.PATH_TOWER_GREY_03,
        IS_OBTAIN = true,
        ID = 3,
        RARITY = 2,
        TYPE = 1,
        NAME = "",
        LEVEL = 1,
        SKILLS = {

        },
        ATK_TARGET = 1,
        ATK = 40,
        ATK_UPGRADE = 8,
        ATK_ENHANCE = 20,
        FIRECD = 0.8,
        FIRECD_UPGRADE = 0.01,
        FIRECD_ENHANCE = 0,
        EXTRA_DAMAGE = 120,
        FATALITY_RATE = 0,
    },
    {
        ICON_PATH = StringDef.PATH_TOWER_04,
        ICON_PATH_GREY = StringDef.PATH_TOWER_GREY_04,
        IS_OBTAIN = true,
        ID = 4,
        RARITY = 1,
        TYPE = 1,
        NAME = "",
        LEVEL = 1,
        SKILLS = {

        },
        ATK_TARGET = 6,
        ATK = 100,
        ATK_UPGRADE = 10,
        ATK_ENHANCE = 100,
        FIRECD = 1,
        FIRECD_UPGRADE = 0,
        FIRECD_ENHANCE = 0,
        EXTRA_DAMAGE = 0,
        FATALITY_RATE = 0,
    },
    {
        ICON_PATH = StringDef.PATH_TOWER_05,
        ICON_PATH_GREY = StringDef.PATH_TOWER_GREY_05,
        IS_OBTAIN = true,
        ID = 5,
        RARITY = 4,
        TYPE = 1,
        NAME = "",
        LEVEL = 1,
        SKILLS = {

        },
        ATK_TARGET = 1,
        ATK = 20,
        ATK_UPGRADE = 3,
        ATK_ENHANCE = 30,
        FIRECD = .6,
        FIRECD_UPGRADE = 0,
        FIRECD_ENHANCE = 0,
        EXTRA_DAMAGE = 0,
        FATALITY_RATE = 0,
    },
    {
        ICON_PATH = StringDef.PATH_TOWER_06,
        ICON_PATH_GREY = StringDef.PATH_TOWER_GREY_06,
        IS_OBTAIN = true,
        ID = 6,
        RARITY = 4,
        TYPE = 1,
        NAME = "",
        LEVEL = 1,
        SKILLS = {

        },
        ATK_TARGET = 1,
        ATK = 35,
        ATK_UPGRADE = 5,
        ATK_ENHANCE = 11,
        FIRECD = 1.2,
        FIRECD_UPGRADE = 0,
        FIRECD_ENHANCE = 0,
        EXTRA_DAMAGE = 35,
        FATALITY_RATE = 0,
    },
    {
        ICON_PATH = StringDef.PATH_TOWER_07,
        ICON_PATH_GREY = StringDef.PATH_TOWER_GREY_07,
        IS_OBTAIN = true,
        ID = 7,
        RARITY = 1,
        TYPE = 1,
        NAME = "",
        LEVEL = 1,
        SKILLS = {

        },
        ATK_TARGET = 1,
        ATK = 20,
        ATK_UPGRADE = 3,
        ATK_ENHANCE = 15,
        FIRECD = .45,
        FIRECD_UPGRADE = 0,
        FIRECD_ENHANCE = 0,
        EXTRA_DAMAGE = 35,
        FATALITY_RATE = 0,
    },
    {
        ICON_PATH = StringDef.PATH_TOWER_08,
        ICON_PATH_GREY = StringDef.PATH_TOWER_GREY_08,
        IS_OBTAIN = true,
        ID = 8,
        RARITY = 3,
        TYPE = 1,
        NAME = "",
        LEVEL = 1,
        SKILLS = {

        },
        ATK_TARGET = 1,
        ATK = 10,
        ATK_UPGRADE = 10,
        ATK_ENHANCE = 10,
        FIRECD = 1.0,
        FIRECD_UPGRADE = 0,
        FIRECD_ENHANCE = 0,
        EXTRA_DAMAGE = 0,
        FATALITY_RATE = 0,
    },
    {
        ICON_PATH = StringDef.PATH_TOWER_09,
        ICON_PATH_GREY = StringDef.PATH_TOWER_GREY_09,
        IS_OBTAIN = true,
        ID = 9,
        RARITY = 1,
        TYPE = 1,
        NAME = "",
        LEVEL = 1,
        SKILLS = {

        },
        ATK_TARGET = 5,
        ATK = 20,
        ATK_UPGRADE = 4,
        ATK_ENHANCE = 0,
        FIRECD = 1.2,
        FIRECD_UPGRADE = 0,
        FIRECD_ENHANCE = 0,
        EXTRA_DAMAGE = 0,
        FATALITY_RATE = 2,
    },
    {
        ICON_PATH = StringDef.PATH_TOWER_10,
        ICON_PATH_GREY = StringDef.PATH_TOWER_GREY_10,
        IS_OBTAIN = false,
        ID = 10,
        RARITY = 4,
        TYPE = 1,
        NAME = "",
        LEVEL = 1,
        SKILLS = {

        },
        ATK_TARGET = 5,
        ATK = 30,
        ATK_UPGRADE = 2,
        ATK_ENHANCE = 10,
        FIRECD = 1.3,
        FIRECD_UPGRADE = 0,
        FIRECD_ENHANCE = 0,
        EXTRA_DAMAGE = 50,
        FATALITY_RATE = 0,
    },
    {
        ICON_PATH = StringDef.PATH_TOWER_11,
        ICON_PATH_GREY = StringDef.PATH_TOWER_GREY_11,
        IS_OBTAIN = false,
        ID = 11,
        RARITY = 3,
        TYPE = 2,
        NAME = "",
        LEVEL = 1,
        SKILLS = {

        },
        ATK_TARGET = 1,
        ATK = 10,
        ATK_UPGRADE = 5,
        ATK_ENHANCE = 10,
        FIRECD = 0.8,
        FIRECD_UPGRADE = 0.02,
        FIRECD_ENHANCE = 0,
        EXTRA_DAMAGE = 0,
        FATALITY_RATE = 0,
    },
    {
        ICON_PATH = StringDef.PATH_TOWER_12,
        ICON_PATH_GREY = StringDef.PATH_TOWER_GREY_12,
        IS_OBTAIN = false,
        ID = 12,
        RARITY = 3,
        TYPE = 2,
        NAME = "",
        LEVEL = 1,
        SKILLS = {

        },
        ATK_TARGET = 1,
        ATK = 30,
        ATK_UPGRADE = 0,
        ATK_ENHANCE = 0,
        FIRECD = 0.8,
        FIRECD_UPGRADE = 0,
        FIRECD_ENHANCE = 0,
        EXTRA_DAMAGE = 0,
        FATALITY_RATE = 0,
    },
    {
        ICON_PATH = StringDef.PATH_TOWER_13,
        ICON_PATH_GREY = StringDef.PATH_TOWER_GREY_13,
        IS_OBTAIN = true,
        ID = 13,
        RARITY = 4,
        TYPE = 2,
        NAME = "",
        LEVEL = 1,
        SKILLS = {

        },
        ATK_TARGET = 1,
        ATK = 10,
        ATK_UPGRADE = 5,
        ATK_ENHANCE = 10,
        FIRECD = 0.8,
        FIRECD_UPGRADE = 0.02,
        FIRECD_ENHANCE = 0,
        EXTRA_DAMAGE = 0,
        FATALITY_RATE = 0,
    },
    {
        ICON_PATH = StringDef.PATH_TOWER_14,
        ICON_PATH_GREY = StringDef.PATH_TOWER_GREY_14,
        IS_OBTAIN = false,
        ID = 14,
        RARITY = 2,
        TYPE = 3,
        NAME = "",
        LEVEL = 1,
        SKILLS = {

        },
        ATK_TARGET = 1,
        ATK = 10,
        ATK_UPGRADE = 5,
        ATK_ENHANCE = 10,
        FIRECD = 1,
        FIRECD_UPGRADE = 0,
        FIRECD_ENHANCE = 0,
        EXTRA_DAMAGE = 0,
        FATALITY_RATE = 0,
    },
    {
        ICON_PATH = StringDef.PATH_TOWER_15,
        ICON_PATH_GREY = StringDef.PATH_TOWER_GREY_15,
        IS_OBTAIN = false,
        ID = 15,
        RARITY = 2,
        TYPE = 3,
        NAME = "",
        LEVEL = 1,
        SKILLS = {

        },
        ATK_TARGET = 1,
        ATK = 10,
        ATK_UPGRADE = 10,
        ATK_ENHANCE = 10,
        FIRECD = 1,
        FIRECD_UPGRADE = 0,
        FIRECD_ENHANCE = 0,
        EXTRA_DAMAGE = 0,
        FATALITY_RATE = 0,
    },
    {
        ICON_PATH = StringDef.PATH_TOWER_16,
        ICON_PATH_GREY = StringDef.PATH_TOWER_GREY_16,
        IS_OBTAIN = false,
        ID = 16,
        RARITY = 3,
        TYPE = 3,
        NAME = "",
        LEVEL = 1,
        SKILLS = {

        },
        ATK_TARGET = 1,
        ATK = 10,
        ATK_UPGRADE = 5,
        ATK_ENHANCE = 10,
        FIRECD = 2,
        FIRECD_UPGRADE = 0,
        FIRECD_ENHANCE = 0,
        EXTRA_DAMAGE = 0,
        FATALITY_RATE = 0,
    },
    {
        ICON_PATH = StringDef.PATH_TOWER_17,
        ICON_PATH_GREY = StringDef.PATH_TOWER_GREY_17,
        IS_OBTAIN = false,
        ID = 17,
        RARITY = 3,
        TYPE = 3,
        NAME = "",
        LEVEL = 1,
        SKILLS = {

        },
        ATK_TARGET = 1,
        ATK = 20,
        ATK_UPGRADE = 5,
        ATK_ENHANCE = 10,
        FIRECD = 1,
        FIRECD_UPGRADE = 0,
        FIRECD_ENHANCE = 0,
        EXTRA_DAMAGE = 0,
        FATALITY_RATE = 0,

    },
    {
        ICON_PATH = StringDef.PATH_TOWER_18,
        ICON_PATH_GREY = StringDef.PATH_TOWER_GREY_18,
        IS_OBTAIN = false,
        ID = 18,
        RARITY = 1,
        TYPE = 3,
        NAME = "",
        LEVEL = 1,
        SKILLS = {

        },
        ATK_TARGET = 5,
        ATK = 30,
        ATK_UPGRADE = 5,
        ATK_ENHANCE = 10,
        FIRECD = 1,
        FIRECD_UPGRADE = 0,
        FIRECD_ENHANCE = 0,
        EXTRA_DAMAGE = 0,
        FATALITY_RATE = 0,
    },
    {
        ICON_PATH = StringDef.PATH_TOWER_19,
        ICON_PATH_GREY = StringDef.PATH_TOWER_GREY_19,
        IS_OBTAIN = true,
        ID = 19,
        RARITY = 4,
        TYPE = 4,
        NAME = "",
        LEVEL = 1,
        SKILLS = {

        },
        ATK_TARGET = 1,
        ATK = 60,
        ATK_UPGRADE = 5,
        ATK_ENHANCE = 20,
        FIRECD = 2,
        FIRECD_UPGRADE = 0,
        FIRECD_ENHANCE = 0,
        EXTRA_DAMAGE = 0,
        FATALITY_RATE = 0,
    },
    {
        ICON_PATH = StringDef.PATH_TOWER_20,
        ICON_PATH_GREY = StringDef.PATH_TOWER_GREY_20,
        IS_OBTAIN = false,
        ID = 20,
        RARITY = 1,
        TYPE = 4,
        NAME = "",
        LEVEL = 1,
        SKILLS = {

        },
        ATK_TARGET = 5,
        ATK = 20,
        ATK_UPGRADE = 5,
        ATK_ENHANCE = 20,
        FIRECD = 1,
        FIRECD_UPGRADE = 0.02,
        FIRECD_ENHANCE = 0,
        EXTRA_DAMAGE = 0,
        FATALITY_RATE = 0,
    },
    TOWER_R_IDLIST = {
        1, 4, 7, 9, 18, 20,
    },
    TOWER_SR_IDLIST = {
        3, 14, 15,
    },
    TOWER_SSR_IDLIST = {
        2, 8, 11, 12, 16, 17
    },
    TOWER_UR_IDLIST = {
        5, 6, 10, 13, 19
    },
}
return TowerDef
