---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Zoybzo.
--- DateTime: 2022-07-07 13:08
---
local TreasureBoxCommodityNode = class("TreasureBoxCommodityNode", function()
    return cc.Node:create()
end)
--local
local audio = require("framework.audio")
local ConstDef = require("app.def.ConstDef")
local StringDef = require("app.def.StringDef")
local Commodity = require("app.data.Commodity")
local OutGameData = require("app.data.OutGameData")
--
--
function TreasureBoxCommodityNode:ctor(commodity)
    self.commodity_ = commodity
    --
    self:initView()
end

function TreasureBoxCommodityNode:initView()
    local itemWidth, itemHeight = ConstDef.SHOP_ITEM_WIDTH, ConstDef.SHOP_ITEM_HEIGHT
    --
    local boxLayer = ccui.Layout:create()
    boxLayer:setAnchorPoint(0.5, 0.5)
    boxLayer:setContentSize(itemWidth * 9 / 2, itemHeight * 3 / 2)
    boxLayer:pos(display.cx, itemHeight / 2)
    boxLayer:addTo(self)
    --
    local boxButton = ccui.Button:create(self.commodity_:getTreasureBoxType())

end

return TreasureBoxCommodityNode