---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Zoybzo.
--- DateTime: 2022-07-05 16:08
---
local DiamondShopLayer = class("DiamondShopLayer", require("app.ui.layer.BaseLayer"))
--local
local Log = require("app.utils.Log")
local StringDef = require("app.def.StringDef")
local OutGameData = require("app.data.OutGameData")
local ConstDef = require("app.def.ConstDef")
local TreasureBoxCommodityNode = require("app.ui.node.TreasureBoxCommodityNode")
--
--local _userInfo -- 本来是想着拿个单例，但是不确定拿过来之后是引用还是拷贝 就没有用这个
--
function DiamondShopLayer:ctor()
    DiamondShopLayer.super.ctor(self)
    --
    self:initView()
end

function DiamondShopLayer:initView()
    local diamondShopLayer = cc.CSLoader:getInstance():createNodeWithFlatBuffersFile("DiamondShopLayer.csb"):addTo(self)
    -- 商品行
    local storeRows = {
        tolua.cast(ccui.Helper:seekWidgetByName(diamondShopLayer, "rowListView1"), "ccui.ListView"),
        tolua.cast(ccui.Helper:seekWidgetByName(diamondShopLayer, "rowListView2"), "ccui.ListView")
    }
    local list = OutGameData:getDiamondShop():getCommodityList()
    for i = 1, #(list) do
        local node
        if list[i]:getCommodityType() == ConstDef.COMMODITY_TYPE.TREASUREBOX then
            node = TreasureBoxCommodityNode.new(list[i])
        else
            -- 出错了
            Log.e("Error Commodity Type in DiamondShopLayer:initView()")
            exit()
        end
        local index = 1
        if i > ConstDef.ROW_COMMODITY_NUMBER then
            index = 2
        end
        --node:addTo(storeRows[index])
        storeRows[index]:pushBackCustomItem(node)
    end
end

function DiamondShopLayer:onEnter()

end

function DiamondShopLayer:onExit()

end

return DiamondShopLayer
