---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Zoybzo.
--- DateTime: 2022-07-05 13:14
---
local ShopBackgroundLayer = class("ShopBackgroundLayer", require("app.ui.layer.BaseLayer"))
--local
local StringDef = require("app.def.StringDef")
--
--

function ShopBackgroundLayer:ctor()
    ShopBackgroundLayer.super.ctor(self)
    --
    self:initView()
end

function ShopBackgroundLayer:initView()
    local sprite = ccui.Layout:create()
    sprite:setBackGroundImage(StringDef.PATH_BACKGROUND_SHOP)
    sprite:setPosition(display.width / 2, display.height / 2)
    sprite:setAnchorPoint(0.5, 0.5)
    sprite:setContentSize(display.width, display.height)
    sprite:addTo(self)
end

function ShopBackgroundLayer:update()

end

function ShopBackgroundLayer:onEnter()

end

function ShopBackgroundLayer:onExit()

end

return ShopBackgroundLayer