---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Zoybzo.
--- DateTime: 2022-07-05 15:00
---
local ShopLayer = class("ShopLayer", require("app.ui.layer.BaseLayer"))
--local
local StringDef = require("app.def.StringDef")
local UserInfo = require("app.data.UserInfo")
local CoinShopLayer = require("app.ui.layer.CoinShopLayer")
local DiamondShopLayer = require("app.ui.layer.DiamondShopLayer")
--
local _userInfo
--

function ShopLayer:ctor()
    ShopLayer.super.ctor(slef)
    --
    self.coinShopLayer_ = nil
    self.diamondShopLayer = nil
    _userInfo = UserInfo.getInstance()
    --
    self:initView()
end

function ShopLayer:initView()
    local itemWidth, itemHeight = display.width / 5, display.height / 6
    local listView = ccui.ListView:create()
    listView:setContentSize(display.width, display.height * 7 / 8) -- 滑动区域大小
    listView:setAnchorPoint(0.5, 0.5)
    listView:setPosition(display.cx, display.cy)
    listView:setDirection(1) -- 垂直
    listView:addTo(self)

    self.coinShopLayer_ = CoinShopLayer.new():addTo(listView)
    self.diamondShopLayer = DiamondShopLayer.new():addTo(listView)
end
