---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Asus.
--- DateTime: 2022/6/21 10:10
---

--[[--
    显示用户奖励进度以及奖励领取信息的层
    UserRewardsLayer.lua
]]
local UserRewardsLayer = class("UserRewardsLayer", function()
    return display.newLayer()
end)

--local
local GameData = require("app.test.GameData")
local CreateSpriteUtil = require("src/app/test/CreateSpriteUtil.lua")
local CalibrateScaleSprite = require("src/app/ui/node/CalibrateScaleSprite.lua")
local Log = require("app.utils.Log")
--
--[[--
    @description: 构造方法
    @param none
    @return none
]]
function UserRewardsLayer:ctor()
    --self.goldenKeyQuantity_ = nil --type: number 用户当前金钥匙数量
    --self.maxGoldenKeyQuantity_ = nil --type: number 最大金钥匙数量
    self.rewardsMap_ = nil -- type: map key = rewardData, value = rewardSprite
    self.calibrateScale_ = nil --type: sprite 用于帧刷新
    self:init()
end

--[[--
    @description:初始化方法
    @param none
    @return none
]]
function UserRewardsLayer:init()
    local spriteBG = display.newSprite("res/home/battle/high_ladder/background.png")
    spriteBG:setPosition(display.width * .46, display.height * 0.75)
    spriteBG:setScale(0.9, 0.7)
    spriteBG:setContentSize(display.width - 20, display.height * .20)
    spriteBG:addTo(self)

    local leftButton = ccui.Button:create("res/home/battle/high_ladder/icon_slide_left.png")
    leftButton:setPosition(30, display.height * .8)
    leftButton:addTouchEventListener(function(sender, eventType)
        print("test left button")
    end)
    leftButton:addTo(self)

    local rightButton = ccui.Button:create("res/home/battle/high_ladder/icon_slide_right.png")
    rightButton:setPosition(display.width - 30, display.height * .8)
    rightButton:addTouchEventListener(function(sender, eventType)
        print("test right button")
    end)
    rightButton:addTo(self)
    --各项属性初始化，暂时保持这样，后面可能会因为需求变化
    --self.goldenKeyQuantity_ = GameData.userKeyQuantity_
    --self.maxGoldenKeyQuantity_ = GameData.maxKeyQuantity_
    self.rewardsMap_ = CreateSpriteUtil:createRewardList(GameData.rewards_)
    --构建天梯列表
    local highLadderView = ccui.ListView:create()
    highLadderView:setPosition(45, display.height * .69)
    highLadderView:setAnchorPoint(0, 0)
    highLadderView:setContentSize(display.width - 90, display.height * .18)
    highLadderView:setDirection(2)
    highLadderView:addTo(self)
    --构建进度条
    local calibrateScale = CalibrateScaleSprite.new("res/home/battle/high_ladder/calibrated scale/calibrated_scale.png",
        GameData.userKeyQuantity_)
    Log.i(" userKeyQuantity_ is " .. tostring(GameData.userKeyQuantity_))
    calibrateScale:setAnchorPoint(0, 0)
    calibrateScale:setPosition(12, 15)
    calibrateScale:addTo(highLadderView)
    self.calibrateScale_ = calibrateScale
    local count = 1
    local size = highLadderView:getContentSize()
    for _, node in pairs(self.rewardsMap_) do
        local spSize = node:getContentSize()

        local itemLayer = ccui.Layout:create()
        itemLayer:setBackGroundColorType(3)
        itemLayer:setAnchorPoint(.5, .5)
        --itemLayer:setPosition(count * 100 + 50, size.height * .5  + 20)
        itemLayer:setContentSize(spSize.width * .8, spSize.height * .8)
        itemLayer:addTo(highLadderView)

        node:setPosition(spSize.width * .4 + 2.5, spSize.height * .4 + 30)
        node:setScale(0.66)
        node:addTo(itemLayer)
        count = count + 1
    end
    --构建钥匙
    local keySprite = display.newSprite("res/home/battle/high_ladder/calibrated scale/key.png")
    keySprite:setPosition(18, 35)
    keySprite:addTo(highLadderView)
end

--[[--
    @description: 帧刷新
    @param dt type:number, 帧间隔
]]
function UserRewardsLayer:update(dt)
    for _, node in pairs(self.rewardsMap_) do
        node:update(dt)
    end
    self.calibrateScale_:update(dt)
end

--[[--
    @description: 执行事件的注册
]]
function UserRewardsLayer:onEnter()

end

--[[--
    @description: 执行事件的注销
]]
function UserRewardsLayer:onExit()

end

return UserRewardsLayer
