---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Asus.
--- DateTime: 2022/7/8 15:56
---
local json = require("src/framework/json.lua")

local table = {
    "string",
    121,
    false,
    true,
    keyStr = "string",
    keyNumber = 214,
    keyFalse = false,
    keyTrue = true,

    keyFunction = function(param)
        print(param)
    end
}

local jsonstr = json.encode(table)
print(jsonstr)