---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Asus.
--- DateTime: 2022/6/21 9:58
---
--[[--
    主界面的战斗界面
    MainUIBattleView.lua
]]

local MainUIBattleView = class("MainUIBattleView", function()
    return display.newColorLayer(cc.c4b(0, 0, 0, 0))
end)
--local
local BattleBackGroundLayer = require("app.ui.layer.BattleBackGroundLayer")
local OutGameBattleLayer = require("app.ui.layer.OutGameBattleLayer")
local TrophyRewardsLayer = require("app.ui.layer.TrophyRewardsLayer")
--
--[[--
    @description: 构造函数
    @param none
    @return none
]]
function MainUIBattleView:ctor()
    self.battleBackGroundLayer_ = nil --type:layer, 背景层
    self.outGameBattleLayer_ = nil --type:layer, 显示战斗按钮和队伍的层
    self.trophyRewardLayer_ = nil --type:layer, 天梯奖励层

    self:initView()
end

function MainUIBattleView:initView()
    self.battleBackGroundLayer_ = BattleBackGroundLayer.new()
    self:addChild(self.battleBackGroundLayer_)
    self.outGameBattleLayer_ = OutGameBattleLayer.new()
    self:addChild(self.outGameBattleLayer_)
    self.trophyRewardLayer_ = TrophyRewardsLayer.new()
    self:addChild(self.trophyRewardLayer_)
end

--[[--
    @description: 执行事件的注册
]]
function MainUIBattleView:onEnter()

end

--[[--
    @description: 执行事件的注销
]]
function MainUIBattleView:onExit()

end

--[[--
    @description:帧刷新
    @param dt type:number, 帧间隔
    @return none
]]
function MainUIBattleView:update(dt)
    self.trophyRewardLayer_:update(dt)
    self.battleBackGroundLayer_:update(dt)
    self.outGameBattleLayer_:update(dt)
end

return MainUIBattleView
