---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Asus.
--- DateTime: 2022/6/21 9:58
---
--[[--
    主界面的战斗界面
    MainUIBattle.lua
]]

local MainUIBattle = class("MainUIBattle", function()
    return display.newColorLayer(cc.c4b(0, 0, 0, 0))
end)
local BattleBackGroundLayer = require("src/app/ui/layer/BattleBackGroundLayer.lua")
local UserBattleLayer = require("src/app/ui/layer/UserBattleLayer.lua")
local UserRewardsLayer = require("src/app/ui/layer/UserRewardsLayer.lua")
--[[--
    @description: 构造函数
    @param none
    @return none
]]
function MainUIBattle:ctor()
    self.battleBackGroundLayer_ = nil --type:layer, 背景层
    self.userBattleLayer_ = nil --type:layer, 显示战斗按钮和队伍的层
    self.userRewardLayer_ = nil --type:layer, 天梯奖励层

    self:initView()
end

function MainUIBattle:initView()
    self.battleBackGroundLayer_ = BattleBackGroundLayer.new()
    self:addChild(self.battleBackGroundLayer_)
    self.userBattleLayer_ = UserBattleLayer.new()
    self:addChild(self.userBattleLayer_)
    self.userRewardLayer_ = UserRewardsLayer.new()
    self:addChild(self.userRewardLayer_)
end

--[[--
    @description: 执行事件的注册
]]
function MainUIBattle:onEnter()

end

--[[--
    @description: 执行事件的注销
]]
function MainUIBattle:onExit()

end

--[[--
    @description:帧刷新
    @param dt type:number, 帧间隔
    @return none
]]
function MainUIBattle:update(dt)
    self.userRewardLayer_:update(dt)
    self.battleBackGroundLayer_:update(dt)
    self.battleBackGroundLayer_:update(dt)
end

return MainUIBattle
