---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Zoybzo.
--- DateTime: 2022-07-05 16:48
---
---把对象包装成商品视图的类
local CommodityNode = class("CommoditySprite", function()
    return cc.Node:create()
end)
--local
local audio = require("framework.audio")
local ConstDef = require("app.def.ConstDef")
local StringDef = require("app.def.StringDef")
local Commodity = require("app.data.Commodity")
local OutGameData = require("app.data.OutGameData")
--
--
function CommodityNode:ctor(commodity)
    self.commodity_ = commodity
    --
    self:initView()
end

function CommodityNode:initView()
    local commodityLayer = ccui.Layout:create()
    commodityLayer:setAnchorPoint(0.5, 0.5)
    commodityLayer:addTo(self)
    -- 本来想的是不论免费的收费的都可以同一到一种框架里面 但是好像基本就是完全不一样
    local button
    -- 第一步：设置背景
    local commodityType = self.commodity_:getCommodityType()
    if commodityType == ConstDef.COMMODITY_TYPE.CURRENCY then
        commodityLayer:setContentSize(ConstDef.SHOP_ITEM_WIDTH * 13 / 9, ConstDef.SHOP_ITEM_HEIGHT)
        --
        button = ccui.Button:create(StringDef.PATH_COIN_SHOP_FREE_DIAMOND)
        button:setPosition(ConstDef.SHOP_ITEM_WIDTH * 2 / 3, ConstDef.SHOP_ITEM_HEIGHT / 2)
        button:setAnchorPoint(0.5, 0.5)
        local size = button:getContentSize()
        button:addTo(commodityLayer)
        -- 根据货币类型填充内容物
        local currencyType = self.commodity_:getCurrencyType()
        local icon
        if currencyType == ConstDef.CURRENCY_TYPE.COIN then
            icon = cc.Sprite:create(StringDef.PATH_COIN_SHOP_COIN)
        elseif currencyType == ConstDef.CURRENCY_TYPE.DIAMOND then
            icon = cc.Sprite:create(StringDef.PATH_COIN_SHOP_DIAMOND)
        else
            -- TODO 感觉非常需要写一个用来报错的函数 但是感觉 lua 不会有反射的 哇超 lua 有反射 可以
            Log.e("Error Currency Type in CommodityNode:initView()")
            exit()
        end
        icon:setPosition(ConstDef.SHOP_ITEM_WIDTH * 2 / 3, ConstDef.SHOP_ITEM_HEIGHT / 5 * 3)
        icon:setAnchorPoint(0.5, 0.5)
        local size = icon:getContentSize()
        icon:addTo(commodityLayer)
        -- 设置货币数量
        local num = display.newTTFLabel({
            text = "x" .. tostring(self.commodity_:getCommodityAmount()),
            font = StringDef.PATH_FONT_FZBIAOZJW,
            size = 24
        })
        num:align(display.CENTER, itemWidth * 2 / 3, itemHeight / 3)
        num:setColor(cc.c3b(173, 196, 255))
        num:enableOutline(cc.c4b(0, 0, 0, 255), 1)
        num:addTo(commodityLayer)
    elseif commodityType == ConstDef.COMMODITY_TYPE.TOWER then
        commodityLayer:setContentSize(ConstDef.SHOP_ITEM_WIDTH * 13 / 9, ConstDef.SHOP_ITEM_HEIGHT)
        --
        -- 根据塔的id填充背景
        button = ccui.Button:create(
                "home/shop/coins_shop/commodity_icon_tower_fragment/" .. self.commodity_:getCardId() .. ".png")
        button:setPosition(ConstDef.SHOP_ITEM_WIDTH * 2 / 3, ConstDef.SHOP_ITEM_HEIGHT / 2)
        button:setAnchorPoint(0.5, 0.5)
        local size = button:getContentSize()
        --button:scale(itemHeight/size.height)
        button:addTo(commodityLayer)
        -- 根据商品数量填充右上角碎片数量
        --碎片底图
        local fragmentBase = cc.Sprite:create(StringDef.PATH_COIN_SHOP_BASE_FRAGMENT)
        fragmentBase:setPosition(size.width * 20 / 19, itemHeight * 5 / 6)
        fragmentBase:setAnchorPoint(1, 0.5)
        local size = fragmentBase:getContentSize()
        --fragmentBase:scale(itemHeight / size.height /6)
        fragmentBase:addTo(commodityLayer)
        -- 碎片数量
        local fragmentNum = display.newTTFLabel({
            text = "x" .. tostring(self.commodity_:getCommodityAmount()),
            font = StringDef.PATH_FONT_FZZCHJW,
            size = 19
        })
        fragmentNum:align(display.CENTER, size.width * 2, itemHeight * 5 / 6)
        fragmentNum:setColor(cc.c3b(255, 206, 55))
        fragmentNum:enableOutline(cc.c4b(0, 0, 0, 255), 1)
        fragmentNum:addTo(commodityLayer)
    elseif commodityType == ConstDef.COMMODITY_TYPE.TREASUREBOX then
        commodityLayer:setContentSize(ConstDef.SHOP_ITEM_WIDTH * 9 / 2, ConstDef.SHOP_ITEM_HEIGHT * 3 / 2)
        --
        button = ccui.Button:create(StringDef.PATH_DIAMOND_SHOP_BASE_RARE)

    else
        Log.e("Error Commodity Type in CommodityNode:initView()")
        exit()
    end
    -- 第二步：判断商品价格
    local price = self.commodity_:getCommodityPrice()
    if price == 0 then
        local priceTitle = cc.Sprite:create(StringDef.PATH_COIN_SHOP_ICON_FREE)
        priceTitle:setPosition(ConstDef.SHOP_ITEM_WIDTH * 2 / 3, ConstDef.SHOP_ITEM_HEIGHT / 6)
        priceTitle:setAnchorPoint(0.5, 0.5)
        local size = priceTitle:getContentSize()
        --priceTitle:scale(itemHeight / size.height /6)
    else
        -- 金币图标
        local coinIcon = cc.Sprite:create(StringDef.PATH_COIN_SHOP_ICON_COIN)
        if self.commodity_:getCardType() == ConstDef.TOWER_RARITY.SSR then
            coinIcon:setPosition(itemWidth * 2 / 3 - 30, itemHeight / 6)
        else
            coinIcon:setPosition(itemWidth * 2 / 3 - 23, itemHeight / 6)
        end
        coinIcon:setAnchorPoint(0.5, 0.5)
        local sizeCoin = coinIcon:getContentSize()
        --coinIcon:scale(itemHeight / sizeCoin.height /6)
        coinIcon:addTo(commodityLayer)
        -- 价格
        local dragonPrice = display.newTTFLabel({
            text = self.commodity_:getCommodityPrice(),
            font = StringDef.PATH_FONT_FZBIAOZJW,
            size = 25
        })
        dragonPrice:align(display.CENTER, ConstDef.SHOP_ITEM_WIDTH * 4 / 5, ConstDef.SHOP_ITEM_HEIGHT / 6)
        dragonPrice:setColor(cc.c3b(255, 255, 255))
        dragonPrice:enableOutline(cc.c4b(0, 0, 0, 255), 1)
        dragonPrice:addTo(commodityLayer)
    end
    -- 第三步：设置点击事件
    -- 首先：免费直接领 付费需要判断
    -- 其次：需要区分不同的商品类型
    if commodityType == ConstDef.COMMODITY_TYPE.CURRENCY then
        button:addTouchEventListener(function(sender, eventType)
            if 0 == eventType then
                Log.i("0")
                commodityLayer:scale(0.8)
            end
            if 2 == eventType then
                Log.i("2")
                audio.playEffect(StringDef.PATH_GET_FREE_ITEM)
                --freeButton:setTouchEnabled(false)
                commodityLayer:scale(1)
            end
        end)
    elseif commodityType == ConstDef.COMMODITY_TYPE.TOWER then
        button:addTouchEventListener(function(sender, eventType)
            if 0 == eventType then
                commodityLayer:scale(0.8)
            end
            if 2 == eventType then
                --dragonButton:setTouchEnabled(false)
                audio.playEffect(StringDef.PATH_GET_PADI_ITEM)
                _buttonCoinClik(rowLayer, itemWidth, itemHeight, dragonButton, dragon)
            end
        end)
    elseif commodityType == ConstDef.COMMODITY_TYPE.TREASUREBOX then
        -- TODO 这块得和原来的代码对照一下 有点不对
        --button:addTouchEventListener(function(sender, eventType)
        --    if 0 == eventType then
        --        commodityLayer:scale(0.8)
        --    end
        --    if 2 == eventType then
        --        --boxLengendButton:setTouchEnabled(false)
        --        audio.playEffect(StringDef.PATH_OPEN_BOX)
        --        rowLegendLayer:scale(1)
        --    end
        --end)
    end
end

return CommodityNode
