---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Zoybzo.
--- DateTime: 2022-07-05 16:36
---
local FreeCoin = class("FreeCoin", function()
    return cc.Node:create()
end)

function FreeCoin:ctor()

    self:initView()
end

function FreeCoin:initView()

end
