---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Asus.
--- DateTime: 2022/6/22 14:14
---
--[[--
    塔节点
    TowerSprite
]]
local TowerSprite = class("towerSprite", function(res)
    return display.newSprite(res)
end)
--local
local StringDef = require("app.def.StringDef")
local Factory = require("app.utils.Factory")
local ConstDef = require("app.def.ConstDef")
--

--[[--
    @description: 构造函数
    @param res type:string 图片资源
    @param data type:Card 塔对象
    @return none
]]
function TowerSprite:ctor(res, data)
    self.data_ = data --type: table,精灵对应的数据

    local towerType = Factory:createTowerType(self.data_.cardType_)
    local towerLevel = Factory:createTowerLevel(self.data_.cardLevel_)

    self.levelSprite_ = towerLevel --type:sprite, 塔等级对应的精灵

    local size = self:getContentSize()
    towerType:setPosition(size.width * .85, size.height)
    towerLevel:setPosition(size.width * .5, -5)
    self:addChild(towerLevel)
    self:addChild(towerType)

end

--[[--
    @description: 帧刷新
    @param dt type:number, 帧间隔，单位秒
    @return none
]]
function TowerSprite:update(dt)
    self.levelSprite_:setTexture(ConstDef.ICON_TOWER_LEVEL_LIST[self.data_:getCardLevel()])
end

return TowerSprite
