---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Zoybzo.
--- DateTime: 2022-07-05 13:10
---
--- 这个类目前只是用来做商品的，个人信息里面完全不需要用这个东西
--- 预定几个属性
--- currencyType_
local Currency = class("Currency", require("app.data.base.BaseModel"))

-- local
local ConstDef = require("app.def.ConstDef")
local EventDef = require("app.def.EventDef")
local EventManager = require("app.manager.EventManager")
--

function Currency:ctor(type, amount)
    self:setCurrency(type, amount)
    EventManager:doEvent(EventDef.ID.CREATE_CARD, self)
end

function Currency:setCurrency(type, amount)
    self.currencyType_ = type
    self.currencyAmount_ = amount
end

function Currency:getCurrencyType()
    return self.currencyType_
end

function Currency:getCurrencyAmount()
    return self.currencyAmount_
end

return Currency
