---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Asus.
--- DateTime: 2022/6/22 9:55
---
--[[--
    用于模拟游戏数据
]]
local CreateSpriteUtil = require("src/app/utils/CreateSpriteUtil.lua")


local GameData = {}

--[[--
    @description: 均为个人开发用测试数据
    @param none
    @return none
]]
function GameData:init()
    self.rewards_ = CreateSpriteUtil:getRewardDataTest()
    self.userKeyQuantity_ = 100
    self.maxKeyQuantity_ = 500
    self.keyRewardNodes_ = CreateSpriteUtil:createRewardNodesTest()
    self.currentTeam_ = CreateSpriteUtil:createTeamTest()
end
--[[--
    @description: 测试用
    @param none
    @return none
]]
function GameData:update()
    --do nothing
end
return GameData