---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Zoybzo.
--- DateTime: 2022-07-05 12:56
---
--[[--
    Shop.lua
    商店
]]
local Shop = class("Shop", require("app.data.base.BaseModel"))

--local
local EventDef = require("app.def.EventDef")
local EventManager = require("app.manager.EventManager")
--

---@param freshTime string 钻石商店可以不传这个
function Shop:ctor(commodityList, freshTime)
    self:setShop(commodityList, freshTime)
    EventManager:doEvent(EventDef.ID.CREATE_STORE, self)
end

function Shop:setShop(commodityList, freshTime)
    self.commodityList_ = commodityList
    self.freshTime_ = freshTime
end

function Shop:getCommodityList()
    return self.commodityList_
end

function Shop:getCoinShopRefreshTime()
    return self.freshTime_
end

function Shop:setCoinShopRefreshTime(freshTime)
    self.freshTime_ = freshTime
end

return Shop
