---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Asus.
--- DateTime: 2022/6/22 9:55
---
--[[--
    用于模拟游戏数据
]]
local GameData = {}
--local
--local CreateSpriteUtil = require("app.test.CreateSpriteUtil")
local TestDataFactory = require("src/app/test/TestDataFactory.lua")
--

--[[--
    @description: 均为个人开发用测试数据
    @param none
    @return none
]]
function GameData:init()
    self.rewards_ = TestDataFactory:getRewardDataTest()
    self.userKeyQuantity_ = 100
    self.maxKeyQuantity_ = 500
    self.keyRewardNodes_ = TestDataFactory:getRewardNodesTest()
    self.currentTeam_ = TestDataFactory:getTeamDataTest()
end

--[[--
    @description: 测试用
    @param none
    @return none
]]
function GameData:update()
    --do nothing
end

return GameData
