---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Zoybzo.
--- DateTime: 2022-05-24 15:42
---

--     LuaPanda.printToVSCode(logStr, printLevel, type)
--         打印日志到VSCode Output下 LuaPanda Debugger 中
--         @printLevel: debug(0)/info(1)/error(2) 这里的日志等级需高于launch.json中配置等级日志才能输出 (可选参数，默认0)
--         @type(可选参数，默认0): 0:VSCode output console  1:VSCode tip  2:VSCode debug console

local Log = {}
--local
local Config = require("app.utils.Config")
--

function Log.i(...)
    if ... == nil then
        print("[LOG_ERRO]" .. " NULLPTR")
    elseif Config.IS_LOG then
        print("[INFO]" .. ...)
    end
end

function Log.e(...)
    if ... == nil then
        print("[LOG_ERRO]" .. " NULLPTR")
    elseif Config.IS_LOG then
        print("[ERROR]", ...)
    end
end

function Log.w(...)
    if ... == nil then
        print("[LOG_ERRO]" .. " NULLPTR")
    elseif Config.IS_LOG then
        print("[WARN]", ...)
    end
end

return Log
