---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Zoybzo.
--- DateTime: 2022-07-12 10:24
---
local TypeConvert = {}

function TypeConvert.Integer2StringLeadingZero(value, number)
    local result = tostring(value)
    local len = #result
    for i = 1, number - len do
        result = "0" .. result
    end
    return result
end

return TypeConvert
